version: '3.8'
services:
  tr-postgres:
    image: postgres:16
    restart: always
    container_name: tr-postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tr-db
    volumes:
      - tr-postgres-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - tr-network

  tr-redis:
    image: redis:7-alpine
    container_name: tr-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - tr-network

  tr-redis-insight:
    image: redislabs/redisinsight:latest
    container_name: tr-redis-insight
    restart: always
    depends_on:
      - tr-redis
    ports:
      - 5540:5540
    networks:
      - tr-network

volumes:
  tr-postgres-db: {}

networks:
  tr-network:
